# Generated by Django 3.0.8 on 2020-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('national', models.IntegerField(default=1234567890, help_text='میتوانید خالی بگذارید', unique=True, verbose_name='کد ملی')),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField(error_messages={'invalid': 'مقدار وارد شده نامعتبر است'}, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, default='reza.ghari@yahoo.com', max_length=254, null=True, verbose_name='ایمیل')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='آپلود مدارک')),
                ('lead', models.CharField(choices=[('Website', 'وبسایت'), ('Instagram', 'اینستاگرام'), ('People', 'معرف'), ('Twitter', 'توییتر'), ('SMS', 'اسمس'), ('Off Add', 'تبلیغات محیطی'), ('On Add', 'تبلیغات آنلاین')], default='وبسایت', max_length=9)),
            ],
        ),
    ]
