# Generated by Django 3.0.8 on 2020-07-08 17:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='national',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(blank=True, help_text='میتوانید چیزی آپلود نکنید', null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='آپلود مدارک'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='محمدرضا قاری', max_length=30, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead',
            field=models.CharField(choices=[('Website', 'وبسایت'), ('Instagram', 'اینستاگرام'), ('People', 'معرف'), ('Twitter', 'توییتر'), ('SMS', 'اسمس'), ('Off Add', 'تبلیغات محیطی'), ('On Add', 'تبلیغات آنلاین')], default='وبسایت', max_length=9, verbose_name='نحوه آشنایی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, default='09120001122', max_length=31, verbose_name='شماره تلفن'),
        ),
    ]
