# Generated by Django 3.0.8 on 2020-07-08 17:35

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200708_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2020-02-02', verbose_name='تاریخ اولین خرید'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='محمدرضا قاری', max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead',
            field=models.CharField(choices=[('Website', 'وبسایت'), ('Instagram', 'اینستاگرام'), ('People', 'معرف'), ('Twitter', 'توییتر'), ('SMS', 'اسمس'), ('Off Add', 'تبلیغات محیطی'), ('On Add', 'تبلیغات آنلاین')], default='وبسایت', max_length=9, verbose_name='نحوه آشنایی با شرکت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, default='09120001122', max_length=11, validators=[dashboard.models.validate_phone], verbose_name='شماره تلفن'),
        ),
    ]
