# Generated by Django 3.0.8 on 2020-07-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200708_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='دوربین مداربسته', max_length=50, verbose_name='نام محصول')),
                ('code', models.CharField(default=10001, max_length=5, verbose_name='کد محصول')),
                ('price', models.IntegerField(default=20000000, help_text='به تومان', max_length=10, verbose_name='قیمت')),
                ('quantity', models.IntegerField(default=1, max_length=4, verbose_name='تعداد موجود')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, default=9120001122, max_length=11, verbose_name='شماره تلفن'),
        ),
    ]
