# Generated by Django 3.0.8 on 2020-07-08 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200708_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField(default=1, max_length=4, verbose_name='تعداد')),
                ('date', models.DateField(default='2020-02-02', verbose_name='تاریخ ثبت')),
                ('total_price', models.IntegerField(help_text='به تومان', max_length=12, verbose_name='قابل پرداخت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer', verbose_name='نام مشتری')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.Product', verbose_name='نوع محصول')),
            ],
        ),
    ]
